# DATA
data:
  window_size: 30
  future_steps: 6
  overlap: True
  threshold: 0.00072
#MODEL
model_technical:
  name: "technical_basic"
  input_dim: 9
  hidden_dim: 2048
  layer_dim: 5
  output_dim: 1
  dropout: 0.2
  loss: 'mse'
  optim: 'adam'
  training:
    learning_rate: 0.000005
    num_epochs: 400

model_fundamental:
  name: "fundamental_basic"
  input_dim: 9
  hidden_dim: 256
  layer_dim: 2
  output_dim: 1
  dropout: 0.2
  loss: 'mse'
  optim: 'adam'
  training:
    learning_rate: 0.0005
    num_epochs: 300

model_combined:
  name: "combined_basic"
  input_dim: 17
  hidden_dim: 512
  layer_dim: 2
  output_dim: 1
  dropout: 0.2
  loss: 'mse'
  optim: 'adam'
  training:
    learning_rate: 0.0005
    num_epochs: 300
