# DATA
data:
  window_size: 10
  overlap: True
  threshold: 0.00072
#MODEL
model_technical:
  name: "technical_combined"
  input_dim: 9
  hidden_dim: 100
  layer_dim: 5
  output_dim: 1
  loss: 'combined'
  optim: 'adam'
  training:
    learning_rate: 0.001
    num_epochs: 300
model_fundamental:
  name: "fundamental_combined"
  input_dim: 9
  hidden_dim: 100
  layer_dim: 5
  output_dim: 1
  loss: 'combined'
  optim: 'adam'
  training:
    learning_rate: 0.001
    num_epochs: 300


