# DATA
data:
  window_size: 20
  future_steps: 6
  overlap: True
  threshold: 0.00072
#MODEL
model_technical:
  name: "technical_combined"
  input_dim: 9
  hidden_dim: 256
  layer_dim: 2
  output_dim: 1
  dropout: 0.2
  loss: 'combined'
  optim: 'adam'
  training:
    learning_rate: 0.0005
    num_epochs: 300
model_fundamental:
  name: "fundamental_combined"
  input_dim: 9
  hidden_dim: 256
  layer_dim: 2
  output_dim: 1
  dropout: 0.2
  loss: 'combined'
  optim: 'adam'
  training:
    learning_rate: 0.0005
    num_epochs: 300
model_combined:
  name: "combined_combined"
  input_dim: 17
  hidden_dim: 512
  layer_dim: 2
  output_dim: 1
  dropout: 0
  loss: 'combined'
  optim: 'adam'
  training:
    learning_rate: 0.0005
    num_epochs: 300
